add float features to multi node
xuewujiao/Paddle pull request #338
Opened 2023-08-10 11:50 UTC by luweipeng

### PR types

### PR changes

### Describe

2023-08-10 12:40 UTC, chao9527 commented on paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
> +    if (infer_mode_) {
此处存在bug,参考最新的 slot feature改下

2023-08-11 03:02 UTC, huwei02 requested changes

2023-08-11 03:02 UTC, huwei02 commented on paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
> +  // loc.alloc(node_num, sizeof(uint64_t) /*key_bytes*/);
无用代码，都清理掉

2023-08-11 03:02 UTC, huwei02 commented on paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
> +
无用空行，也需要清理一下

2023-08-11 03:02 UTC, huwei02 commented on paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
> +    }
如果走到4165行，但是FLAGS_enable_graph_multi_node_sampling为false，是不是有问题，获取不到float_feature了

2023-08-11 03:02 UTC, huwei02 commented on paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
> +__global__ void fill_vari_float_feature_and_slot(float* dst_feature_list,
可以尝试用模板来解决fill_vari_feature_and_slot和fill_vari_float_feature_and_slot的diff，没必要重新复制一遍代码

2023-08-11 03:02 UTC, huwei02 commented on paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
> +  size_t pull_size = 0;
这个没必要单独写一行了，直接和4213行合并吧

2023-08-11 03:02 UTC, huwei02 commented on paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
> +
同上

2023-08-11 03:02 UTC, huwei02 commented on paddle/fluid/framework/fleet/heter_ps/graph_gpu_ps_table_inl.cu
> +int GpuPsGraphTable::get_float_feature_info_of_nodes_all2all(
你看一下能否复用已有代码（get_feature_info_of_nodes_all2all），可以对已有代码进行改造，方便复用，而不重拷贝重写，后者不是一个好的编码习惯，会增加后续维护成本。

2023-08-15 08:09 UTC, merged